branches:
  only:
    - master

version: "{build}"

shallow_clone: true

environment:
  nodejs_version: "0.12"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - node_modules/.bin/gulp vendor:twitter-text
  - npm run travis
