branches:
  only:
    - master

version: "{build}"

shallow_clone: true

install:
  - ps: Install-Product node 0.12.3 amd64
  - npm install

build: off

before_script: |
  node --version
  npm --version
  node_modules/.bin/gulp vendor:twitter-text

test_script: npm run travis
