language: node_js

node_js:
  - "iojs"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script: node_modules/.bin/gulp vendor:twitter-text

script: npm run travis
